#!/bin/bash
git init -qqq
git remote add origin https://github.com/walkwizus/docker-marello
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/* ./
mv compose/.gitignore ./
rm -rf compose .git
git init

# Ensure these are created so Docker doesn't create them as root
mkdir -p ~/.composer ~/.ssh