version: "3"

services:
  app:
    volumes: &appvolumes
      - ./resources/nginx/nginx.conf.sample:/var/www/html/nginx.conf:cached

  phpfpm:
    volumes: *appvolumes

  ssh:
    image: walkwizus/ssh
    ports:
      - "22:22"
    volumes: *appvolumes